export const citationConstants = {
    SENDCITATIONMAIL_REQUEST: "SENDCITATIONMAIL_REQUEST",
    SENDCITATIONMAIL_SUCCESS: "SENDCITATIONMAIL_SUCCESS",
    SENDCITATIONMAIL_FAILURE: "SENDCITATIONMAIL_FAILURE",
    ENDCITATIONALERTS: "ENDCITATIONALERTS",
};
