export const generatorConstants = {
    GENERATORCITATION_REQUEST: "GENERATORCITATION_REQUEST",
    GENERATORCITATION_SUCCESS: "GENERATORCITATION_SUCCESS",
    GENERATORCITATION_FAILURE: "GENERATORCITATION_FAILURE",
    REDIRECTTOCITATIONS: "REDIRECTTOCITATIONS",

    GENERATORMINUTE_REQUEST: "GENERATORMINUTE_REQUEST",
    GENERATORMINUTE_SUCCESS: "GENERATORMINUTE_SUCCESS",
    GENERATORMINUTE_FAILURE: "GENERATORMINUTE_FAILURE",

    RESETACTION_MINUTE: "RESETACTION_MINUTE",
};
