export const mailConstants = {
    GETMAILPERMITS_REQUEST: "GETMAILPERMITS_REQUEST",
    GETMAILPERMITS_SUCCESS: "GETMAILPERMITS_SUCCESS",
    GETMAILPERMITS_FAILURE: "GETMAILPERMITS_FAILURE",

    GETMAILS_REQUEST: "GETMAILS_REQUEST",
    GETMAILS_SUCCESS: "GETMAILS_SUCCESS",
    GETMAILS_FAILURE: "GETMAILS_FAILURE",

    GETMAIL_REQUEST: "GETMAIL_REQUEST",
    GETMAIL_SUCCESS: "GETMAIL_SUCCESS",
    GETMAIL_FAILURE: "GETMAIL_FAILURE",

    DELETEMAIL_REQUEST: "DELETEMAIL_REQUEST",
    DELETEMAIL_SUCCESS: "DELETEMAIL_SUCCESS",
    DELETEMAIL_FAILURE: "DELETEMAIL_FAILURE",

    CREATEMAIL_REQUEST: "CREATEMAIL_REQUEST",
    CREATEMAIL_SUCCESS: "CREATEMAIL_SUCCESS",
    CREATEMAIL_FAILURE: "CREATEMAIL_FAILURE",

    UPDATEMAIL_REQUEST: "UPDATEMAIL_REQUEST",
    UPDATEMAIL_SUCCESS: "UPDATEMAIL_SUCCESS",
    UPDATEMAIL_FAILURE: "UPDATEMAIL_FAILURE",
    
    CLOSEMODAL_ALLMODALSMAILS: "CLOSEMODAL_ALLMODALSMAILS",
    CREATEMAILCLOSEMODAL: "CREATEMAILCLOSEMODAL",
    OPENCREATEMAILMODAL: "OPENCREATEMAILMODAL",
}