export const rolConstant = {
    GETROLES_REQUEST: "GETROLES_REQUEST",
    GETROLES_SUCCESS: "GETROLES_SUCCESS",
    GETROLES_FAILURE: "GETROLES_FAILURE",

    GETROL_REQUEST: "GETROL_REQUEST",
    GETROL_SUCCESS: "GETROL_SUCCESS",
    GETROL_FAILURE: "GETROL_FAILURE",

    UPDATEROL_REQUEST: "UPDATEROL_REQUEST",
    UPDATEROL_SUCCESS: "UPDATEROL_SUCCESS",
    UPDATEROL_FAILURE: "UPDATEROL_FAILURE",

    DELETEROL_REQUEST: "DELETEROL_REQUEST",
    DELETEROL_SUCCESS: "DELETEROL_SUCCESS",
    DELETEROL_FAILURE: "DELETEROL_FAILURE",

    ADDROLES_REQUEST: "ADDROLES_REQUEST",
    ADDROLES_SUCCESS: "ADDROLES_SUCCESS",
    ADDROLES_FAILURE: "ADDROLES_FAILURE",

    GETROLINFO_REQUEST: "GETROLINFO_REQUEST",
    GETROLINFO_SUCCESS: "GETROLINFO_SUCCESS",
    GETROLINFO_FAILURE: "GETROLINFO_FAILURE",

    GETROLCAPACITIES_REQUEST: "GETROLCAPACITIES_REQUEST",
    GETROLCAPACITIES_SUCCESS: "GETROLCAPACITIES_SUCCESS",
    GETROLCAPACITIES_FAILURE: "GETROLCAPACITIES_FAILURE",

    SETSELECTEDROL: "SETSELECTEDROL",
    FINISHUPDATE: "FINISHUPDATE",
    FINISHDELETE: "FINISHDELETE",
};
