export const searchConstants = {
    SEARCHAPPRETICE_REQUEST: "SEARCHAPPRETICE_REQUEST",
    SEARCHAPPRETICE_SUCCESS: "SEARCHAPPRETICE_SUCCESS",
    SEARCHAPPRETICE_FAILURE: "SEARCHAPPRETICE_FAILURE",

    SEARCHINSTRUCTOR_REQUEST: "SEARCHINSTRUCTOR_REQUEST",
    SEARCHINSTRUCTOR_SUCCESS: "SEARCHINSTRUCTOR_SUCCESS",
    SEARCHINSTRUCTOR_FAILURE: "SEARCHINSTRUCTOR_FAILURE",

    SEARCHONEAPRETICE_REQUEST: "SEARCHONEAPRETICE_REQUEST",
    SEARCHONEAPRETICE_SUCCESS: "SEARCHONEAPRETICE_SUCCESS",
    SEARCHONEAPRETICE_FAILURE: "SEARCHONEAPRETICE_FAILURE",

    SEARCHONEINSTRUCTOR_REQUEST: "SEARCHONEINSTRUCTOR_REQUEST",
    SEARCHONEINSTRUCTOR_SUCCESS: "SEARCHONEINSTRUCTOR_SUCCESS",
    SEARCHONEINSTRUCTOR_FAILURE: "SEARCHONEINSTRUCTOR_FAILURE",

    FINISHSEARCHED: "FINISHSEARCHED",

    HIDESEARCHEDMODAL: "HIDESEARCHEDMODAL",
};
