export const solicityConstants = {
    GETSOLICITYDRAW_REQUEST: "GETSOLICITYDRAW_REQUEST",
    GETSOLICITYDRAW_SUCCESS: "GETSOLICITYDRAW_SUCCESS",
    GETSOLICITYDRAW_FAILURE: "GETSOLICITYDRAW_FAILURE",

    GETSOLICITIES_REQUEST: "GETSOLICITIES_REQUEST",
    GETSOLICITIES_SUCCESS: "GETSOLICITIES_SUCCESS",
    GETSOLICITIES_FAILURE: "GETSOLICITIES_FAILURE",

    GETSOLICITIE_REQUEST: "GETSOLICITIE_REQUEST",
    GETSOLICITIE_SUCCESS: "GETSOLICITIE_SUCCESS",
    GETSOLICITIE_FAILURE: "GETSOLICITIE_FAILURE",
    GETSOLICITIE_CLOSE_MODAL: "GETSOLICITIE_CLOSE_MODAL",

    SAVESOLICITY_REQUEST: "SAVESOLICITY_REQUEST",
    SAVESOLICITY_SUCCESS: "SAVESOLICITY_SUCCESS",
    SAVESOLICITY_FAILURE: "SAVESOLICITY_FAILURE",
    SAVESOLICITY_FINISH: "SAVESOLICITY_FINISH",

    CHANGESOLICITYSTATUS_REQUEST: "CHANGESOLICITYSTATUS_REQUEST",
    CHANGESOLICITYSTATUS_SUCCESS: "CHANGESOLICITYSTATUS_SUCCESS",
    CHANGESOLICITYSTATUS_FAILURE: "CHANGESOLICITYSTATUS_FAILURE",

    GETMOTIVESORPROHIBITIONS_REQUEST: "GETMOTIVESORPROHIBITIONS_REQUEST",
    GETMOTIVESORPROHIBITIONS_SUCCESS: "GETMOTIVESORPROHIBITIONS_SUCCESS",
    GETMOTIVESORPROHIBITIONS_FAILURE: "GETMOTIVESORPROHIBITIONS_FAILURE",

    GETMOTIVESORPROHIBITION_REQUEST: "GETMOTIVESORPROHIBITION_REQUEST",
    GETMOTIVESORPROHIBITION_SUCCESS: "GETMOTIVESORPROHIBITION_SUCCESS",
    GETMOTIVESORPROHIBITION_FAILURE: "GETMOTIVESORPROHIBITION_FAILURE",
    CLOSEMOTIVEORPROHIBITION: "CLOSEMOTIVEORPROHIBITION",

    SAVEMOTIVESORPROHIBITIONS_REQUEST: "SAVEMOTIVESORPROHIBITIONS_REQUEST",
    SAVEMOTIVESORPROHIBITIONS_SUCCESS: "SAVEMOTIVESORPROHIBITIONS_SUCCESS",
    SAVEMOTIVESORPROHIBITIONS_FAILURE: "SAVEMOTIVESORPROHIBITIONS_FAILURE",

    SAVEMOTIVESORPROHIBITIONS_FINISH: "SAVEMOTIVESORPROHIBITIONS_FINISH",

    UPDATEMOTIVESORPROHIBITIONS_REQUEST: "UPDATEMOTIVESORPROHIBITIONS_REQUEST",
    UPDATEMOTIVESORPROHIBITIONS_SUCCESS: "UPDATEMOTIVESORPROHIBITIONS_SUCCESS",
    UPDATEMOTIVESORPROHIBITIONS_FAILURE: "UPDATEMOTIVESORPROHIBITIONS_FAILURE",

    DELETEMOTIVESORPROHIBITIONS_REQUEST: "DELETEMOTIVESORPROHIBITIONS_REQUEST",
    DELETEMOTIVESORPROHIBITIONS_SUCCESS: "DELETEMOTIVESORPROHIBITIONS_SUCCESS",
    DELETEMOTIVESORPROHIBITIONS_FAILURE: "DELETEMOTIVESORPROHIBITIONS_FAILURE",
}