export const templateConstants = {
    GETCUSTOMFIELDS_REQUEST: "GETCUSTOMFIELDS_REQUEST",
    GETCUSTOMFIELDS_SUCCESS: "GETCUSTOMFIELDS_SUCCESS",
    GETCUSTOMFIELDS_FAILURE: "GETCUSTOMFIELDS_FAILURE",

    CREATETEMPLATE_REQUEST: "CREATETEMPLATE_REQUEST",
    CREATETEMPLATE_SUCCESS: "CREATETEMPLATE_SUCCESS",
    CREATETEMPLATE_FAILURE: "CREATETEMPLATE_FAILURE",
    FINISH_CREATE_TEMPLATE: "FINISH_CREATE_TEMPLATE",

    GETTEMPLATES_REQUEST: "GETTEMPLATES_REQUEST",
    GETTEMPLATES_SUCCESS: "GETTEMPLATES_SUCCESS",
    GETTEMPLATES_FAILURE: "GETTEMPLATES_FAILURE",

    GETTEMPLATE_REQUEST: "GETTEMPLATE_REQUEST",
    GETTEMPLATE_SUCCESS: "GETTEMPLATE_SUCCESS",
    GETTEMPLATE_FAILURE: "GETTEMPLATE_FAILURE",

    UPDATETEMPLATE_REQUEST: "UPDATETEMPLATE_REQUEST",
    UPDATETEMPLATE_SUCCESS: "UPDATETEMPLATE_SUCCESS",
    UPDATETEMPLATE_FAILURE: "UPDATETEMPLATE_FAILURE",

    DELETETEMPLATE_REQUEST: "DELETETEMPLATE_REQUEST",
    DELETETEMPLATE_SUCCESS: "DELETETEMPLATE_SUCCESS",
    DELETETEMPLATE_FAILURE: "DELETETEMPLATE_FAILURE",

    SHOWMODAL: "SHOWMODAL",
    HIDEMODAL: "HIDEMODAL",
}