export const uploadConstants = {
    APPRENTICESUPLOAD_REQUEST: "APPRENTICESUPLOAD_REQUEST",
    APPRENTICESUPLOAD_SUCCESS: "APPRENTICESUPLOAD_SUCCESS",
    APPRENTICESUPLOAD_FAILURE: "APPRENTICESUPLOAD_FAILURE",

    APPRENTICESINGLEUPLOAD_REQUEST: "APPRENTICESINGLEUPLOAD_REQUEST",
    APPRENTICESINGLEUPLOAD_SUCCESS: "APPRENTICESINGLEUPLOAD_SUCCESS",
    APPRENTICESINGLEUPLOAD_FAILURE: "APPRENTICESINGLEUPLOAD_FAILURE",
    APPRENTICESINGLEUPLOAD_FINISH: "APPRENTICESINGLEUPLOAD_FINISH",

    UPLOADNEWFILESOLICITY_REQUEST: "UPLOADNEWFILESOLICITY_REQUEST",
    UPLOADNEWFILESOLICITY_SUCCESS: "UPLOADNEWFILESOLICITY_SUCCESS",
    UPLOADNEWFILESOLICITY_FAILURE: "UPLOADNEWFILESOLICITY_FAILURE",
    UPLOADNEWFILESOLICITY_CLEAR: "UPLOADNEWFILESOLICITY_CLEAR",

    UPLOADALERT_HIDE: "UPLOADALERT_HIDE",
};
