export const userConstants = {
    USERLOGIN_REQUEST: "USERLOGIN_REQUEST",
    USERLOGIN_SUCCESS: "USERLOGIN_SUCCESS",
    USERLOGIN_FAILURE: "USERLOGIN_FAILURE",
    USERLOGOUT: "USERLOGOUT",

    USERREGISTER_REQUEST: "USERREGISTER_REQUEST",
    USERREGISTER_SUCCESS: "USERREGISTER_SUCCESS",
    USERREGISTER_FAILURE: "USERREGISTER_FAILURE",

    SEARCHUSER_REQUEST: "SEARCHUSER_REQUEST",
    SEARCHUSER_SUCCESS: "SEARCHUSER_SUCCESS",
    SEARCHUSER_FAILURE: "SEARCHUSER_FAILURE",

    GETSEARCHEDUSER_REQUEST: "GETSEARCHEDUSER_REQUEST",
    GETSEARCHEDUSER_SUCCESS: "GETSEARCHEDUSER_SUCCESS",
    GETSEARCHEDUSER_FAILURE: "GETSEARCHEDUSER_FAILURE",

    EDITSEARCHEDUSER_REQUEST: "EDITSEARCHEDUSER_REQUEST",
    EDITSEARCHEDUSER_SUCCESS: "EDITSEARCHEDUSER_SUCCESS",
    EDITSEARCHEDUSER_FAILURE: "EDITSEARCHEDUSER_FAILURE",

    GETMYCITATIONS_REQUEST: "GETMYCITATIONS_REQUEST",
    GETMYCITATIONS_SUCCESS: "GETMYCITATIONS_SUCCESS",
    GETMYCITATIONS_FAILURE: "GETMYCITATIONS_FAILURE",

    GETSELECTEDCITATION_REQUEST: "GETSELECTEDCITATION_REQUEST",
    GETSELECTEDCITATION_SUCCESS: "GETSELECTEDCITATION_SUCCESS",
    GETSELECTEDCITATION_FAILURE: "GETSELECTEDCITATION_FAILURE",
    GETSELECTEDCITATION_HIDEMODAL: "GETSELECTEDCITATION_HIDEMODAL",

    UPLOADNEWCITATIONSTATUS_REQUEST: "UPLOADNEWCITATIONSTATUS_REQUEST",
    UPLOADNEWCITATIONSTATUS_SUCCESS: "UPLOADNEWCITATIONSTATUS_SUCCESS",
    UPLOADNEWCITATIONSTATUS_FAILURE: "UPLOADNEWCITATIONSTATUS_FAILURE",
    UPLOADNEWCITATIONSTATUS_HIDEMODAL: "UPLOADNEWCITATIONSTATUS_HIDEMODAL",

    USERUPDATEPASSWORD_REQUEST: "USERUPDATEPASSWORD_REQUEST",
    USERUPDATEPASSWORD_SUCCESS: "USERUPDATEPASSWORD_SUCCESS",
    USERUPDATEPASSWORD_FAILURE: "USERUPDATEPASSWORD_FAILURE",

    USER_LOGOUT: "USER_LOGOUT",
};
